/**
 * Production-facing legal documents. The master pack is not a public document.
 * Triggers decide where a document is accepted. Screens must not hard-code document ids.
 */

export type LegalCatalogEntry = {
  key: string;
  file: string;
  title: string;
  version: string;
  effectiveDate: string;
  jurisdiction: string;
  roleScope: string;
  featureTrigger: string;
  requiresAcceptance: boolean;
  acknowledgementOnly: boolean;
  category: "core" | "creators" | "businesses" | "safety" | "enterprise";
};

export const LEGAL_CATEGORIES: { id: LegalCatalogEntry["category"]; label: string }[] = [
  { id: "core", label: "Core" },
  { id: "creators", label: "Influencers" },
  { id: "businesses", label: "Businesses" },
  { id: "safety", label: "Safety & rights" },
  { id: "enterprise", label: "Enterprise" },
];

const V = "1.1";
const DAY = "2026-09-30";

export const LEGAL_CATALOG: LegalCatalogEntry[] = [
  {
    key: "terms-of-service",
    file: "terms-of-service.txt",
    title: "Terms of Service",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "all",
    featureTrigger: "registration",
    requiresAcceptance: true,
    acknowledgementOnly: false,
    category: "core",
  },
  {
    key: "electronic-consent",
    file: "electronic-consent.txt",
    title: "User Registration & Electronic Consent Agreement",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "all",
    featureTrigger: "registration",
    requiresAcceptance: true,
    acknowledgementOnly: false,
    category: "core",
  },
  {
    key: "privacy-policy",
    file: "privacy-policy.txt",
    title: "Privacy Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "all",
    featureTrigger: "registration",
    requiresAcceptance: false,
    acknowledgementOnly: true,
    category: "core",
  },
  {
    key: "cookie-policy",
    file: "cookie-policy.txt",
    title: "Cookie & Tracking Technologies Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "core",
  },
  {
    key: "creator-terms",
    file: "creator-terms.txt",
    title: "Influencer Terms",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "creator",
    featureTrigger: "creator_claim",
    requiresAcceptance: true,
    acknowledgementOnly: false,
    category: "creators",
  },
  {
    key: "social-platform-integration-terms",
    file: "social-platform-integration-terms.txt",
    title: "Social Platform Integration & Connected Accounts Terms",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "creator",
    featureTrigger: "creator_claim",
    requiresAcceptance: true,
    acknowledgementOnly: false,
    category: "creators",
  },
  {
    key: "connected-social-data-policy",
    file: "connected-social-data-policy.txt",
    title: "Connected Social Data & API Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "creator",
    featureTrigger: "social_connect",
    requiresAcceptance: false,
    acknowledgementOnly: true,
    category: "creators",
  },
  {
    key: "card-terms",
    file: "card-terms.txt",
    title: "Influrios Card Terms",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "creator",
    featureTrigger: "card_activation",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "creators",
  },
  {
    key: "advertising-disclosure-policy",
    file: "advertising-disclosure-policy.txt",
    title: "Influencer Advertising Disclosure & Endorsement Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "creator",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "creators",
  },
  {
    key: "business-terms",
    file: "business-terms.txt",
    title: "Business / Brand Terms",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "business",
    featureTrigger: "business_registration",
    requiresAcceptance: true,
    acknowledgementOnly: false,
    category: "businesses",
  },
  {
    key: "marketplace-terms",
    file: "marketplace-terms.txt",
    title: "Collaboration Marketplace Terms",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "all",
    featureTrigger: "collaboration",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "businesses",
  },
  {
    key: "protected-payments-policy",
    file: "protected-payments-policy.txt",
    title: "Protected Collaboration Payments, Fees, Payouts & Disputes Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "all",
    featureTrigger: "protected_payment",
    requiresAcceptance: false,
    acknowledgementOnly: true,
    category: "businesses",
  },
  {
    key: "subscription-terms",
    file: "subscription-terms.txt",
    title: "Subscription, Billing, Cancellation & Refund Terms",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "all",
    featureTrigger: "subscription_checkout",
    requiresAcceptance: true,
    acknowledgementOnly: false,
    category: "core",
  },
  {
    key: "public-profile-policy",
    file: "public-profile-policy.txt",
    title: "Public Profile & Data Collection Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "profile-removal-policy",
    file: "profile-removal-policy.txt",
    title: "Profile Claim, Correction, Opt-Out & Removal Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "community-guidelines",
    file: "community-guidelines.txt",
    title: "Community Guidelines & Acceptable Use Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "dmca-policy",
    file: "dmca-policy.txt",
    title: "Copyright & DMCA Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "identity-verification-policy",
    file: "identity-verification-policy.txt",
    title: "Identity, Image, Impersonation & Verification Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "complaints-appeals-policy",
    file: "complaints-appeals-policy.txt",
    title: "Complaints, Appeals & Enforcement Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "take-it-down-policy",
    file: "take-it-down-policy.txt",
    title: "Nonconsensual Intimate Imagery / Take It Down Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "ai-processing-policy",
    file: "ai-processing-policy.txt",
    title: "AI & Automated Processing Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "age-eligibility-policy",
    file: "age-eligibility-policy.txt",
    title: "Age Eligibility & Minor Influencer Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "safety",
  },
  {
    key: "security-disclosure-policy",
    file: "security-disclosure-policy.txt",
    title: "Security & Responsible Disclosure Policy",
    version: V,
    effectiveDate: DAY,
    jurisdiction: "global",
    roleScope: "public",
    featureTrigger: "public",
    requiresAcceptance: false,
    acknowledgementOnly: false,
    category: "enterprise",
  },
];

export function documentsForTrigger(
  docs: LegalCatalogEntry[],
  trigger: string,
  kind: "acceptance" | "acknowledgement",
) {
  return docs.filter((doc) => {
    if (doc.featureTrigger !== trigger) return false;
    if (kind === "acceptance") return doc.requiresAcceptance && !doc.acknowledgementOnly;
    return doc.acknowledgementOnly;
  });
}
